[keyboard]
name = "Corne_rmk"
product_name = "Corne_rmk"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Rev01ution"
chip = "nrf52840"

[layout]
rows = 4
cols = 12
layers = 8
keymap = [
    [
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Backspace"],
        ["LCtrl", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "Escape"],
        [ "1", "2", "3","4", "5", "6", "7", "8", "9","0", "1", "2"]
    ],
]

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
row_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
col_pins = ["P1_11", "P1_13", "P1_15", "P0_02", "P0_29", "P0_31"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
row_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
col_pins = ["P1_11", "P1_13", "P1_15", "P0_02", "P0_29", "P0_31"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

# [[split.peripheral]]
# rows = 2
# cols = 1
# row_offset = 2
# col_offset = 2
# serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
# row_pins = ["PIN_9", "PIN_11"]
# col_pins = ["PIN_10"]

[rmk]
split_peripherals_num = 1
